### ISSUE TITLE
add new fields to the users table

### ISSUE THREAD

**Issue by heron2014** [brainsandbrawns/api#15]
Add following:
- [x] created_at (timestamp) - what is the best option to store dates in postgres
- [x] active (Boolean)
- [ ] does password need to be restricted, e.g: 6 characters, 1 digit etc? investigate best practise?

**Comment by sohilpandya** [comment]
check this feature out for postgresql -> https://www.postgresql.org/docs/9.0/static/passwordcheck.html for weening out the weak passwords.

**Comment by heron2014** [comment]
Email validation in postgres: http://stackoverflow.com/questions/5689718/how-can-i-create-a-constraint-to-check-if-an-email-is-valid-in-postgres

**Comment by heron2014** [comment]
Password restriction I am leaving it for now.

**Comment by heron2014** [comment]
Resolved #26
